# 07 — Research Module: Scientific Productivity Forecast
**EduForecast** | OpenAlex API | Notebook 7

Forecasts yearly publication counts for Astana IT University using the public OpenAlex API, comparing Prophet `growth='linear'` vs `growth='logistic'`.

**Scope limitation (read before trusting any number below):** this fits on **6 complete yearly data points** (2020-2025; 2019 excluded, see cell below; 2026 is a partial year and is kept separately, never used for training or evaluation). That is far too little data for a high-precision forecast — confidence intervals are wide by construction, and the only validation performed is a single leave-last-year-out sanity check, not cross-validation. Treat this as a proof-of-concept for the modelling pipeline, not a production-grade forecast.

In [1]:
import sys
import warnings
from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import pandas as pd

warnings.filterwarnings('ignore')

PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.research.aggregate import build_yearly_counts, filter_training_window, partial_years, to_prophet_frame
from src.research.config import (
    FIGURES_DIR, METRICS_DIR, OPENALEX_INSTITUTION_NAME,
    TRAINING_YEAR_MIN, TRAINING_YEAR_MAX, PARTIAL_YEAR, LOGISTIC_CAP_MULTIPLIER,
)
from src.research.forecast import run_forecast_comparison

print(f'Institution: {OPENALEX_INSTITUTION_NAME}')
print(f'Training window: {TRAINING_YEAR_MIN}-{TRAINING_YEAR_MAX} (complete years only)')
print(f'Partial year (excluded from training and evaluation): {PARTIAL_YEAR}')

Institution: Astana IT University
Training window: 2020-2025 (complete years only)
Partial year (excluded from training and evaluation): 2026

## 1. Collect & Aggregate (OpenAlex)

In [2]:
full_counts = build_yearly_counts()
full_counts

   year  works_count  is_partial
0  2019            1       False
1  2020           26       False
2  2021           83       False
3  2022          156       False
4  2023          252       False
5  2024          416       False
6  2025          606       False
7  2026          753        True

In [3]:
# 2019 is excluded: a single indexed publication that year reflects the
# institution's pre-registration/startup period, not an actual annual
# publication rate. Including it would distort both the trend fit and
# the logistic cap computed below.
# The current year is incomplete (data as of the snapshot date), so it is
# kept separately and never used for training or evaluation.
training = filter_training_window(full_counts)
partial = partial_years(full_counts)
print('Partial (not used):')
print(partial.to_string(index=False))
training

Partial (not used):
 year  works_count  is_partial
 2026          753        True

   year  works_count  is_partial
0  2020           26       False
1  2021           83       False
2  2022          156       False
3  2023          252       False
4  2024          416       False
5  2025          606       False

## 2. Forecast: linear vs logistic growth

The logistic variant needs a saturating `cap`. There is no way to derive this from 6 points, so it is set explicitly as an **expert guess** (current peak × 2, see `src/research/config.py::LOGISTIC_CAP_MULTIPLIER`), not a value fit from the data.

In [4]:
comparison = run_forecast_comparison(training, partial=partial)
print(f'Logistic cap (expert guess): {comparison.logistic_cap:.0f}')
comparison.linear_forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(4)

12:19:27 - cmdstanpy - INFO - Chain [1] start processing

12:19:27 - cmdstanpy - INFO - Chain [1] done processing

12:19:27 - cmdstanpy - INFO - Chain [1] start processing

12:19:27 - cmdstanpy - INFO - Chain [1] done processing

12:19:27 - cmdstanpy - INFO - Chain [1] start processing

12:19:27 - cmdstanpy - INFO - Chain [1] done processing

12:19:27 - cmdstanpy - INFO - Chain [1] start processing

12:19:27 - cmdstanpy - INFO - Chain [1] done processing

Logistic cap (expert guess): 1212

          ds        yhat  yhat_lower  yhat_upper
5 2025-01-01  541.853241  483.027435  601.648716
6 2026-01-01  655.869145  596.119431  714.467356
7 2027-01-01  769.885049  711.312018  830.303145
8 2028-01-01  883.900954  824.710705  944.853295

In [5]:
comparison.logistic_forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(4)

          ds         yhat   yhat_lower   yhat_upper
5 2025-01-01   607.868237   597.875977   618.503305
6 2026-01-01   801.195212   791.055646   810.718201
7 2027-01-01   958.460189   948.535226   969.067533
8 2028-01-01  1066.457283  1056.190662  1077.506773

In [6]:
fig, ax = plt.subplots(figsize=(9, 5))
ax.plot(training['year'], training['works_count'], 'o-', color='#0f172a', label='Факт')
ax.plot(partial['year'], partial['works_count'], 'o', color='#0f172a', markerfacecolor='white',
        markersize=8, label='Неполный год (не в обучении)')

last_year = training['year'].max()
for fcst, label, color in (
    (comparison.linear_forecast, 'Прогноз (linear)', '#2563eb'),
    (comparison.logistic_forecast, 'Прогноз (logistic)', '#059669'),
):
    future = fcst[fcst['ds'].dt.year > last_year].copy()
    future['year'] = future['ds'].dt.year
    ax.plot(future['year'], future['yhat'], '--o', color=color, label=label)
    ax.fill_between(future['year'], future['yhat_lower'], future['yhat_upper'], color=color, alpha=0.15)

ax.axhline(comparison.logistic_cap, color='#6b7280', linestyle=':', linewidth=1,
           label=f'Logistic cap (expert guess) = {comparison.logistic_cap:.0f}')
ax.set_xlabel('Год'); ax.set_ylabel('Публикаций в год')
ax.set_title(f'{OPENALEX_INSTITUTION_NAME}: прогноз научной продуктивности')
ax.legend()
fig.tight_layout()
fig.savefig(FIGURES_DIR / '07_forecast_comparison.png', dpi=150)
plt.show()

## 3. Backtest (sanity check, NOT cross-validation)

Train on 2020-2024, predict 2025, compare against the actual observed 2025 count. The partial year 2026 is not used. With only 6 complete yearly points there is not enough data for a statistically meaningful k-fold or time-series cross-validation — this is a single held-out-year sanity check, named as such on purpose.

In [7]:
bt = comparison.backtest
print(f'Backtest year: {bt.backtest_year}')
print(f'Actual: {bt.actual:.0f}')
print()
for growth, res in bt.predictions.items():
    print(f"{growth:10s} predicted={res['predicted']:6.0f}  "
          f"[{res['lower']:.0f}, {res['upper']:.0f}]  "
          f"abs_error={res['abs_error']:6.1f}  pct_error={res['pct_error']:5.1f}%")
print()
print(bt.note)

Backtest year: 2025
Actual: 606

linear     predicted=   471  [435, 508]  abs_error= 134.7  pct_error= 22.2%
logistic   predicted=   564  [552, 575]  abs_error=  42.2  pct_error=  7.0%

Leave-last-year-out sanity check on a single held-out point: train on complete years up to the year before, predict the last complete year. The partial current year is never used. NOT k-fold or time-series cross-validation: with only 6 complete yearly observations there isn't enough data for a statistically meaningful CV.

In [8]:
backtest_df = pd.DataFrame([
    {'growth': g, 'backtest_year': bt.backtest_year, 'actual': bt.actual, **res}
    for g, res in bt.predictions.items()
])
backtest_df.to_csv(METRICS_DIR / 'research_backtest.csv', index=False)
backtest_df

,growth,backtest_year,actual,predicted,lower,upper,abs_error,pct_error
0,linear,2025,606.0,471.333252,434.981384,508.177987,134.666748,22.222236
1,logistic,2025,606.0,563.761667,552.282849,574.707660,42.238333,6.970022

## 4. Summary

- Data source: OpenAlex API, institution ID `I4405257690` (Astana IT University), aggregated at the whole-institution level (no per-department breakdown — OpenAlex doesn't expose clean sub-institution IDs; see PROJECT_STATUS.md §4.4).
- Training window: 2020-2025 (6 complete years), 2019 dropped as a non-representative startup-period outlier. 2026 is partial and is kept separately, never used for training or evaluation.
- Two Prophet variants compared: `linear` (no ceiling) and `logistic` (ceiling = expert-guessed cap, not data-derived).
- Validation: one leave-last-year-out sanity check, explicitly not a cross-validation, given the small N.
- **This is a proof-of-concept.** Revisit the logistic cap and re-run the backtest once a few more years of data are available.